[phases.setup]
nixPkgs = ["nodejs"]
# Force Railway redeploy to use start:combined script

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:combined"

[variables]
DATA_DIR = "/data"
PORT = "8080" 